version: "3"

services:
  php:
    image: tikiwiki-php
    volumes:
      - ./src:/var/www/html
    depends_on:
            - db
    deploy:
      placement:
        constraints: [node.role == manager]
  web:
    image: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    ports:
      - 8080:80/tcp
    depends_on:
            - php
    deploy:
      placement:
        constraints: [node.role == manager]
  db:
    image: mariadb:5
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=wikidb
      - MYSQL_USER=wikiuser
      - MYSQL_PASSWORD=wikipass
    volumes:
      - db-data:/var/lib/mysql
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  db-data:
