version: "3"

services:
  webphp:
    image: tikiwiki-webphp:dev
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80
    deploy:
      placement:
        constraints: [node.role == manager]
  db:
    image: mariadb:10.1
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=tikidb
      - MYSQL_USER=tikiuser
      - MYSQL_PASSWORD=tikipass
    volumes:
      - db-data:/var/lib/mysql
    depends_on:
      - webphp
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  db-data:
